language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
matrix:
  fast_finish: true
before_install:
- pip install coveralls pylint
install:
- sed -ie "s#test-5.1#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap-buildout.py
- bin/buildout annotate
- bin/buildout
script:
- bin/code-analysis
- bin/test
- pylint --py3k --disable=no-absolute-import src/plone/importexport
after_success:
- bin/createcoverage --output-dir=htmlcov
- coveralls
notifications:
  email:
    - ebrehault@gmail.com
